console.log('Hello World')
console.log('45')
console.log('my favourite number' + 9)
console.log(9+9)
console.log('9'+9)
console.log("added a new file in branch a ")
console.log('amar sonar bangla ami tomay valobasi')