console.log('Hello World')
console.log('45')
console.log('my favourite number' + 9)
console.log(9+9)
console.log('9'+9)
console.log('amar sonar bangla ami tomay valobasi')
console.log('the system is working well')